services:
  compiler-explorer:
    build:
      context: ./
      dockerfile: Dockerfile
    image: dr.devsh.eu/compiler-explorer/windows:latest
    container_name: dev.ce.base
    networks:
      docker_default:
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    ports:
      - "80:10240"

networks:
  docker_default:
    external: true
